### ISSUE TITLE
smbpasswd is not installed in "samba::server" at centos 7

### ISSUE THREAD

**Issue by bigwheel** [jtimberman/samba-cookbook#27]
I tried to use this cookbook in centos7.0 64bit.
But it causes an error as "smbpasswd not fouond".
[smbpasswd command not found on CentOS 7 and RHEL 7](http://sharadchhetri.com/2014/10/07/smbpasswd-command-found-centos-7-rhel-7/)
In centos7.0, samba::server recipes needed to install "samba-client" package.

I know this recipe don't support centos7.0 officially, plz close if this annoys.

**Comment by jtimberman** [comment]
You need to include the samba::client recipe on your node or role run list.
