### ISSUE TITLE
Kill the data bag!!

### ISSUE THREAD

**Issue by meringu** [jtimberman/samba-cookbook#33]
The logic in `samba::server` should be pulled out into a lwrp. Then I can use this cookbook in my environment cookbook with out having to manage more data bags (pain in the back).

The example in the readme would become something like
```ruby
samba_share 'export' do
  comment 'Exported Share'
  path '/srv/export'
  guest_ok false
  printable false
  write_list ['jtimberman']
  create_mask 0664
  directory_mask 0775
end
```

**Comment by jtimberman** [comment]
See #35 and #36.
